### ISSUE TITLE
exception with websocket

### ISSUE THREAD

**Issue by focode** [truongsinh/dart-websocket#2]
I am trying to run this code from the example:
```
import 'package:puppeteer/puppeteer.dart';

void main() async {
  // Download the Chromium binaries, launch it and connect to the "DevTools"
  var browser = await puppeteer.launch();

  // Open a new tab
  var myPage = await browser.newPage();

  // Go to a page and wait to be fully loaded
  await myPage.goto('https://www.github.com', wait: Until.networkIdle);

  // Do something... See other examples
  await myPage.screenshot();
//  await myPage.pdf();
  await myPage.evaluate('() => document.title');

  // Gracefully close the browser's process
  await browser.close();
}
```

and I am getting this exception:
```
Unhandled exception:
Exception: Websocket url not found
#0      _waitForWebSocketUrl (package:puppeteer/src/puppeteer.dart:311:3)
<asynchronous suspension>
#1      Puppeteer.launch (package:puppeteer/src/puppeteer.dart:170:30)
<asynchronous suspension>
#2      main (file:///D:/project/IOT-KT/dl/puppy1/test/puppy1_test.dart:8:33)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by truongsinh** [comment]
Thank you for reporting. I'm traveling right now, and will get back to this soon.

**Comment by paveltretyakovru** [comment]
The same situation after upgrade ubuntu. I have tried to .local-chromium and .dart_tool, but the same result.
